version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ats-resume-checker:latest
    container_name: ats-resume-checker
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PORT=5000
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    labels:
      - "com.example.description=ATS Resume Checker Application"
      - "com.example.version=1.0"

networks:
  app-network:
    driver: bridge

volumes:
  uploads:
  logs:
